stages:
  - imagebuild

before_script:
  - export APP_REVISION="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME##*/}-r$CI_PIPELINE_ID}"

imagebuild:
  stage: imagebuild
  variables:
    KUBECONFIG_YAML: $KUBECONFIG_DEV
  script:
    - |
      # build
      npm config set user 0
      npm config set unsafe-perm true
      npm config set registry=https://registry.npm.taobao.org
#      npm install || exit 1
      npm install yarn tyarn -g
      tyarn
      TERM=xterm npm run build

      # docker build
      IMAGES="$(jq -r '. | map(.server + "/" + .pathPrefix + "/" + env.CI_PROJECT_NAME + ":" + env.APP_REVISION) | join(" ")'<<<"$REGISTRIES")"
      echo $IMAGES
      eval docker build --network=host -t "$IMAGES" . || exit 1

      # docker push
      export DOCKER_CONFIG_JSON="$(jq 'reduce .[].auth.auths as $item ({}; . + $item) | {auths: .}'<<<"$REGISTRIES")"
      echo $DOCKER_CONFIG_JSON
      while read IMAGE; do
        docker push "$IMAGE" || exit 1
      done < <(jq -r '.[] | .server + "/" + .pathPrefix + "/" + env.CI_PROJECT_NAME + ":" + env.APP_REVISION'<<<"$REGISTRIES")

      # docker rmi
      docker images | grep "$APP_REVISION" | grep "$CI_PROJECT_NAME" | awk '{print $3}' | head -n 1 | xargs -t docker rmi -f

      # patch image in dev cluster
      # harbor.musiconline-dev.service.163.org/cloudnative/library/horizon-web:develop-r889445
      KKK='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"'${IMAGES}'"}]'
      kubectl patch deploy horizon-web -n horizon --type='json' -p="$KKK"
  only:
    - develop
    - tags
